-- Auto-generated from schema-map-postgres.psd1 (map@38d5403)
-- engine: postgres
-- table:  payment_gateway_notifications
CREATE TABLE IF NOT EXISTS payment_gateway_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id VARCHAR(255) NOT NULL,
  received_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_pg_notify_version CHECK (version >= 0),
  processing_by VARCHAR(100) NULL,
  processing_until TIMESTAMPTZ(6) NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error VARCHAR(255) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  CONSTRAINT ux_pg_notify_tx UNIQUE (transaction_id),
  CONSTRAINT chk_pg_notify_status CHECK (status IN ('pending','processing','done','failed')),
  CONSTRAINT chk_pg_notify_attempts CHECK (attempts >= 0)
);
